__version__ = "v0.2.0"

from repl.command_handler import dispatch_repl_command, ReplCompleter, REPL_COMMANDS, CmdSignal
from repl.dialogue_utils import dialogue_to_text, parse_dialogue_text
from repl.state_manager import create_initial_state, reset_sop_state
from repl.session_manager import (
    create_session_dir,
    write_run_summary,
    save_session,
    load_session,
    list_sessions,
    delete_session,
    generate_session_id,
)
from repl.sop_runner import run_sop_graph
from repl.ui_renderer import (
    print_welcome,
    print_user_message,
    print_agent_message,
    print_command_result,
)
from repl.app_builder import (
    create_input_field,
    create_top_status_bar,
    create_status_bar,
    create_root_container,
    create_layout,
    build_application,
)
from repl.session_picker import (
    create_picker_state,
    get_picker_condition,
    create_picker_control,
    activate_picker,
    deactivate_picker,
    picker_move_up,
    picker_move_down,
    picker_page_left,
    picker_page_right,
    picker_select,
    picker_cancel,
)
from repl.sop_picker import (
    create_sop_picker_state,
    get_sop_picker_condition,
    create_sop_picker_control,
    activate_sop_picker,
    deactivate_sop_picker,
    sop_picker_enter,
    sop_picker_cancel,
    sop_picker_move_up,
    sop_picker_move_down,
    sop_picker_page_left,
    sop_picker_page_right,
    SOP_PICKER_HEIGHT,
)
from repl.llm_runner import run_llm_node, fmt_elapsed
from repl.compaction_controller import run_chat_compactor, try_auto_compact
from repl.session_controller import (
    save_current_if_dirty,
    restore_session_fields,
    handle_new_session,
    handle_show_picker,
    handle_load_session,
    handle_show_sop_picker,
)
from repl.execution_controller import execute_sop_flow
from repl.keybindings import create_keybindings
from repl.config_manager import get_config, reset_defaults, apply_config
from utils.tts_engine import tts_say
from repl.config_picker import (
    create_config_picker_state,
    get_config_picker_condition,
    create_config_picker_control,
    activate_config_picker,
    deactivate_config_picker,
    config_picker_enter,
    config_picker_cancel,
    config_picker_move_up,
    config_picker_move_down,
    config_picker_adjust,
    CONFIG_PICKER_HEIGHT,
)
from repl.command_hint import (
    create_command_hint_state,
    get_command_hint_condition,
    create_command_hint_control,
    COMMAND_HINT_HEIGHT,
)

__all__ = [
    "__version__",
    "dispatch_repl_command",
    "ReplCompleter",
    "REPL_COMMANDS",
    "CmdSignal",
    "dialogue_to_text",
    "parse_dialogue_text",
    "create_initial_state",
    "reset_sop_state",
    "create_session_dir",
    "write_run_summary",
    "save_session",
    "load_session",
    "list_sessions",
    "delete_session",
    "generate_session_id",
    "run_sop_graph",
    "print_welcome",
    "print_user_message",
    "print_agent_message",
    "print_command_result",
    "create_input_field",
    "create_top_status_bar",
    "create_status_bar",
    "create_root_container",
    "create_layout",
    "build_application",
    "create_picker_state",
    "get_picker_condition",
    "create_picker_control",
    "activate_picker",
    "deactivate_picker",
    "picker_move_up",
    "picker_move_down",
    "picker_page_left",
    "picker_page_right",
    "picker_select",
    "picker_cancel",
    "create_sop_picker_state",
    "get_sop_picker_condition",
    "create_sop_picker_control",
    "activate_sop_picker",
    "deactivate_sop_picker",
    "sop_picker_enter",
    "sop_picker_cancel",
    "sop_picker_move_up",
    "sop_picker_move_down",
    "sop_picker_page_left",
    "sop_picker_page_right",
    "SOP_PICKER_HEIGHT",
    "run_llm_node",
    "fmt_elapsed",
    "run_chat_compactor",
    "try_auto_compact",
    "save_current_if_dirty",
    "restore_session_fields",
    "handle_new_session",
    "handle_show_picker",
    "handle_load_session",
    "handle_show_sop_picker",
    "execute_sop_flow",
    "create_keybindings",
    "get_config",
    "reset_defaults",
    "apply_config",
    "create_config_picker_state",
    "get_config_picker_condition",
    "create_config_picker_control",
    "activate_config_picker",
    "deactivate_config_picker",
    "config_picker_enter",
    "config_picker_cancel",
    "config_picker_move_up",
    "config_picker_move_down",
    "config_picker_adjust",
    "CONFIG_PICKER_HEIGHT",
    "create_command_hint_state",
    "get_command_hint_condition",
    "create_command_hint_control",
    "COMMAND_HINT_HEIGHT",
    "tts_say",
]


